server:
  port: 8082
  servlet:
    context-path: /api
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        jdbc:
          time_zone: UTC

  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 20MB
      location:
  application:
    name: LMS
    version: 1.0.0

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

jwt:
  secret:
    key: ${JWT_SECRET}
  access:
    expiration: 3600000
  refresh:
    expiration: 604800000

app:
  cors:
    allowed-origins:
      - ${FRONTEND_URL}
  file:
    storage:
      path: C:/lms-test/files

password:
  reset:
    link: ${FRONTEND_URL}/reset-password
    token:
      expiration: 86400000


#spring:
#  datasource:
#    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@${DB_NAME}_high?TNS_ADMIN=${OCI_WALLET_PATH}
#    username: ${DB_USER}
#    password: ${DB_PASS}
#    hikari:
#      maxLifetime: 1800000      # 30 minutes (Oracle closes after 30m)
#      idleTimeout: 300000       # 5 minutes
#      validationTimeout: 5000   # 5 seconds
#      connectionTimeout: 30000  # 30 seconds
#      minimumIdle: 5
#      maximumPoolSize: 10
#    tomcat:
#      test-while-idle: true
#      validation-query: SELECT 1 FROM DUAL